import type { PackageType } from "./types"

export const packages: PackageType[] = [
  {
    id: "basic-hourly",
    name: "Basic Hourly",
    description: "Quick access for light browsing",
    price: 20,
    duration: "hour",
    speed: 5,
    validityDays: 1,
    features: ["Email & messaging", "Basic web browsing"],
  },
  {
    id: "standard-hourly",
    name: "Standard Hourly",
    description: "Faster speeds for better experience",
    price: 50,
    duration: "hour",
    speed: 10,
    validityDays: 1,
    features: ["Social media", "Video streaming (SD)"],
  },
  {
    id: "basic-daily",
    name: "Basic Daily",
    description: "Affordable daily access",
    price: 100,
    duration: "day",
    speed: 10,
    validityDays: 1,
    features: ["Email & messaging", "Social media", "Video streaming (SD)"],
  },
  {
    id: "standard-daily",
    name: "Standard Daily",
    description: "Better speeds for all-day use",
    price: 200,
    duration: "day",
    speed: 25,
    validityDays: 1,
    features: ["Video streaming (HD)", "Online gaming", "File downloads"],
  },
  {
    id: "premium-daily",
    name: "Premium Daily",
    description: "High-speed daily access",
    price: 300,
    duration: "day",
    speed: 50,
    validityDays: 1,
    features: ["Video streaming (4K)", "Fast downloads", "Multiple devices"],
  },
  {
    id: "basic-weekly",
    name: "Basic Weekly",
    description: "Affordable weekly plan",
    price: 500,
    duration: "week",
    speed: 15,
    validityDays: 7,
    features: ["Email & messaging", "Social media", "Video streaming (SD)"],
  },
  {
    id: "standard-weekly",
    name: "Standard Weekly",
    description: "Better speeds for the whole week",
    price: 800,
    duration: "week",
    speed: 30,
    validityDays: 7,
    features: ["Video streaming (HD)", "Online gaming", "Multiple devices"],
    popular: true,
  },
  {
    id: "premium-weekly",
    name: "Premium Weekly",
    description: "High-speed weekly access",
    price: 1200,
    duration: "week",
    speed: 50,
    validityDays: 7,
    features: ["Video streaming (4K)", "Fast downloads", "Multiple devices"],
  },
  {
    id: "standard-monthly",
    name: "Standard Monthly",
    description: "Great value for a full month",
    price: 2500,
    duration: "month",
    speed: 30,
    validityDays: 30,
    features: ["Video streaming (HD)", "Online gaming", "Multiple devices"],
  },
  {
    id: "premium-monthly",
    name: "Premium Monthly",
    description: "Ultimate speed for power users",
    price: 3500,
    duration: "month",
    speed: 100,
    validityDays: 30,
    features: ["Video streaming (4K)", "Fast downloads", "Multiple devices", "Priority support"],
  },
]

